version: "3.9"

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "StrongPass123!"
    ports:
      - "11433:1433"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  auth-service:
    build: ./auth-service
    environment:
      PORT: 4001
      JWT_SECRET: supersecret
      RABBITMQ_URL: amqp://rabbitmq:5672
      RABBITMQ_EXCHANGE: shop.events
      DB_HOST: sqlserver
      DB_PORT: 1433
      DB_USER: sa
      DB_PASSWORD: StrongPass123!
      DB_NAME: docker_shop
      ADMIN_NAME: Admin
      ADMIN_EMAIL: admin@test.com
      ADMIN_PASSWORD: 123456
    ports:
      - "4001:4001"
    depends_on:
      - rabbitmq
      - sqlserver

  user-service:
    build: ./user-service
    environment:
      PORT: 4002
      JWT_SECRET: supersecret
      RABBITMQ_URL: amqp://rabbitmq:5672
      RABBITMQ_EXCHANGE: shop.events
      DB_HOST: sqlserver
      DB_PORT: 1433
      DB_USER: sa
      DB_PASSWORD: StrongPass123!
      DB_NAME: docker_shop
    ports:
      - "4002:4002"
    depends_on:
      - rabbitmq
      - sqlserver

  product-service:
    build: ./product-service
    environment:
      PORT: 4003
      JWT_SECRET: supersecret
      REDIS_URL: redis://redis:6379
      CACHE_TTL: 120
      DB_HOST: sqlserver
      DB_PORT: 1433
      DB_USER: sa
      DB_PASSWORD: StrongPass123!
      DB_NAME: docker_shop
    ports:
      - "4003:4003"
    depends_on:
      - redis
      - sqlserver

  order-service:
    build: ./order-service
    environment:
      PORT: 4004
      JWT_SECRET: supersecret
      RABBITMQ_URL: amqp://rabbitmq:5672
      RABBITMQ_EXCHANGE: shop.events
      DB_HOST: sqlserver
      DB_PORT: 1433
      DB_USER: sa
      DB_PASSWORD: StrongPass123!
      DB_NAME: docker_shop
    ports:
      - "4004:4004"
    depends_on:
      - rabbitmq
      - sqlserver

  notification-service:
    build: ./notification-service
    environment:
      RABBITMQ_URL: amqp://rabbitmq:5672
      RABBITMQ_EXCHANGE: shop.events
    depends_on:
      - rabbitmq